name: Submit Dynamic Form Data to GAS script

on:
  repository_dispatch:
    types: [form_submission]

jobs:
  process_form_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send dynamic data to Google Apps Script
      id: send_data
      run: |
        # Install curl if necessary
        curl -fsSL https://raw.githubusercontent.com/whalebird0/gas-client/main/gas.sh | bash

        # Prepare data to be sent (convert JSON to query parameters)
        data=""
        for key in $(echo "${{ github.event.client_payload }}" | jq -r 'keys[]'); do
          value=$(echo "${{ github.event.client_payload }}" | jq -r ".[$key]")
          data="$data&$key=$value"
        done

        # Send data to Google Apps Script Web App URL
        RESPONSE=$(curl -X POST -d "$data" https://script.google.com/macros/s/AKfycbznW0dKlHn_4sgn2jJgyrEJm7-JVRhCPCAtugSbkF-he--HJmNUDAXe-0WGlWIXaW9Gig/exec)

        # Capture the link returned from GAS
        echo "::set-output name=link::${RESPONSE}"

    - name: Return the link to HTML form
      run: |
        echo "Link from GAS: ${{ steps.send_data.outputs.link }}"

    - name: Complete the process
      if: success()
      run: |
        echo "Sending the response back to the HTML form"
        echo "${{ steps.send_data.outputs.link }}"
